
SELECT 
      TASK.TASK_ID AS task_id
  	, TASK.TASK_NM AS task_nm
    , EMP.EMP_NM AS emp_nm
    , EMP.EMP_NO AS emp_no
    , COALESCE(EMP.IP, '0.0.0.0') AS ip 
    , COALESCE(ANS.EMP_ANS_YN, 'N') AS emp_ans_yn 
    , ANS.ANS_DT AS ans_dt 
FROM TB_EMP EMP
LEFT JOIN TB_COMP_EMP_ANS ANS  
      ON EMP.EMP_NO = ANS.EMP_NO 
  	AND (ANS.DEL_YN = 'N' or ANS.DEL_YN is null )
LEFT JOIN TB_COMP_TASK_APP_DT CTAD
  	ON CTAD.TASK_ID = ANS.TASK_ID
	AND CTAD.APP_SEQ = ANS.APP_SEQ
  	AND (CTAD.DEL_YN = 'N' or CTAD.DEL_YN is null )
LEFT JOIN TB_COMP_TASK TASK
	ON TASK.TASK_ID = CTAD.TASK_ID
  	AND (TASK.DEL_YN = 'N' or  TASK.DEL_YN is null )
ORDER BY EMP.EMP_NM ASC;





