spring:
  datasource:
    # url: jdbc:postgresql://127.0.0.1:5432/postgres
    url: jdbc:postgresql://10.201.106.35:5432/postgres
    username: postgres
    password: 'kbds1!'
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Asia/Seoul
  servlet:
    multipart:
      max-file-size: 20MB     # 📌 파일 1개당 최대 업로드 용량
      max-request-size: 20MB  # 📌 한 요청(여러 파일 포함) 전체의 최대 업로드 용량

logging:
  level:
    root: info                    # 📌 프로젝트 전체의 기본 로그를 터미널에 출력 (info 레벨)
    com.kbds.compliance: debug    # 📌 우리가 짠 코드 내부의 SQL 쿼리와 로그는 더 상세히(debug) 출력
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 콘솔 포맷 지정

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:8501
    - http://10.201.106.35